# Generated by Django 3.0.13 on 2021-03-15 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_post_testfield'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='testField',
        ),
        migrations.AddField(
            model_name='post',
            name='body',
            field=models.TextField(default='Default Body'),
        ),
    ]
